name: CI
on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - uses: golangci/golangci-lint-action@v3

  build:
    name: Build and Run
    runs-on: ${{ matrix.os }}
    needs: lint
    strategy:
      fail-fast: true
      matrix:
        os: [macos-latest]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - run: go build ./cmd/semantic-release/
        env:
          CGO_ENABLED: 0
      - run: go test -v ./...
      - run: ./semantic-release --dry --allow-no-changes --no-ci
        env:
          G_TOKEN: ${{ secrets.G_TOKEN }}
        shell: bash

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - run: go build ./cmd/semantic-release/
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.G_TOKEN }}
      - uses: go-semantic-release/action@v1
        with:
          bin: ./semantic-release
          hooks: goreleaser,npm-binary-releaser
          prerelease: true
        env:
          G_TOKEN: ${{ secrets.G_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
