name: CI
on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - uses: go-semantic-release/action@v1
        id: semrel
        with:
          github-token: ${{ secrets.TOKEN }}
          update-file: package.json
          changelog-generator-opt: "emojis=true"
      - run: go build ./cmd/semantic-release/
        env:
          CGO_ENABLED: 0
      - run: go test -v ./...
      - run: ./semantic-release --dry --allow-no-changes --no-ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
